name: flutter_application_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9

  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/weather/
    - assets/icons/system/
    - assets/gifs/
