// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphMiZVN5aZoq-Zn8mj8Yh8g1dZr3NL4Y',
    appId: '1:770739813196:web:661a34b92d6b28554c2de9',
    messagingSenderId: '770739813196',
    projectId: 'sl-flood-mate',
    authDomain: 'sl-flood-mate.firebaseapp.com',
    storageBucket: 'sl-flood-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWhCzXmL-7voqKtZMjFACSwBbduLVF8kE',
    appId: '1:770739813196:android:f96c5dae702f4c434c2de9',
    messagingSenderId: '770739813196',
    projectId: 'sl-flood-mate',
    storageBucket: 'sl-flood-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX9Oou4shqUubjnE-Hvt8WNrZcy_LPGgo',
    appId: '1:770739813196:ios:4e87d4a501029a884c2de9',
    messagingSenderId: '770739813196',
    projectId: 'sl-flood-mate',
    storageBucket: 'sl-flood-mate.appspot.com',
    iosBundleId: 'com.slfloodmate.slFloodMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX9Oou4shqUubjnE-Hvt8WNrZcy_LPGgo',
    appId: '1:770739813196:ios:cd30f815422a8c294c2de9',
    messagingSenderId: '770739813196',
    projectId: 'sl-flood-mate',
    storageBucket: 'sl-flood-mate.appspot.com',
    iosBundleId: 'com.slfloodmate.slFloodMate.RunnerTests',
  );
}
